linters:
  enable:
    - bodyclose
    - copyloopvar
    - exhaustruct
    - gofumpt
    - goimports
    - gosec
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
